# Generated by Django 4.0.2 on 2022-10-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('title_2', models.CharField(blank=True, max_length=100, null=True)),
                ('description_one', models.TextField(blank=True, null=True)),
                ('description_two', models.TextField(blank=True, null=True)),
                ('about_avatar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Drive Image Id')),
            ],
            options={
                'verbose_name_plural': 'AboutMe',
            },
        ),
        migrations.CreateModel(
            name='HomeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('par_inro', models.TextField(blank=True, null=True)),
                ('avatar_img', models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Drive Image Id')),
                ('hireMe_link', models.URLField(blank=True, null=True)),
                ('cv_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'HomeDetails',
            },
        ),
        migrations.CreateModel(
            name='MyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=90, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'MyContact',
            },
        ),
        migrations.CreateModel(
            name='MyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=40, null=True)),
                ('percentage', models.IntegerField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name_plural': 'MyProgress',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_used', models.CharField(blank=True, max_length=100, null=True)),
                ('about_avatar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Drive Image Id')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('Project_title', models.CharField(blank=True, max_length=90, null=True)),
                ('Project_info', models.TextField(blank=True, null=True)),
                ('project_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_avatar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Drive Image Id')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesOffred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_image', models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Drive Image Id')),
                ('service_name', models.CharField(blank=True, max_length=40, null=True)),
                ('shadow_icon', models.CharField(blank=True, max_length=40, null=True)),
                ('service_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'ServicesOffred',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('social_icon', models.CharField(blank=True, max_length=60, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'SocialMediaLinks',
            },
        ),
    ]
