# Generated by Django 4.1.2 on 2022-10-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialMediaLinks',
            new_name='SocialMediaLinks2',
        ),
    ]
