# Generated by Django 4.0.2 on 2022-10-04 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectImages',
        ),
    ]
