# Generated by Django 4.0.2 on 2022-10-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0002_delete_projectimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name_plural': 'About Me Section'},
        ),
        migrations.AlterModelOptions(
            name='homedetails',
            options={'verbose_name_plural': 'Heros Section'},
        ),
        migrations.AlterModelOptions(
            name='mycontact',
            options={'verbose_name_plural': 'Contacts Section'},
        ),
        migrations.AlterModelOptions(
            name='myprogress',
            options={'verbose_name_plural': 'Skills Section'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Projects Section'},
        ),
        migrations.AlterModelOptions(
            name='servicesoffred',
            options={'verbose_name_plural': 'Services Section'},
        ),
        migrations.AlterModelOptions(
            name='socialmedialinks',
            options={'verbose_name_plural': 'Social Media Links'},
        ),
        migrations.RemoveField(
            model_name='mycontact',
            name='icon',
        ),
        migrations.AddField(
            model_name='project',
            name='demo_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
