# Generated by Django 4.1.2 on 2022-10-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0002_rename_socialmedialinks_socialmedialinks2'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedialinks2',
            name='name_te',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
