# Generated by Django 4.0.2 on 2022-09-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0003_alter_homedetails_hireme_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myprogress',
            options={'verbose_name_plural': 'Skills Section'},
        ),
    ]
