# Generated by Django 4.0.2 on 2022-10-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0003_alter_aboutme_options_alter_homedetails_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguagesIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
