# Generated by Django 4.0.2 on 2022-09-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0004_alter_myprogress_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedetails',
            name='avatar_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Home Right Image'),
        ),
    ]
