# Generated by Django 4.0.2 on 2022-10-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0004_languagesicons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languagesicons',
            options={'verbose_name_plural': 'Languages Icons'},
        ),
        migrations.AddField(
            model_name='languagesicons',
            name='lang_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
