# Generated by Django 4.1.2 on 2022-10-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0004_remove_socialmedialinks2_name_te'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedialinks2',
            name='social_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
