# Generated by Django 4.0.2 on 2022-09-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0005_alter_homedetails_avatar_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedetails',
            name='avatar_img',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Drive Image Id'),
        ),
    ]
