# Generated by Django 4.1.2 on 2022-10-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0005_socialmedialinks2_social_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedialinks2',
            old_name='social_link',
            new_name='link',
        ),
    ]
