# Generated by Django 4.0.2 on 2022-10-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0006_mycontact_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedetails',
            name='hireMe_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
