# Generated by Django 4.0.2 on 2022-09-06 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0006_alter_homedetails_avatar_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycontact',
            name='icon',
        ),
    ]
