# Generated by Django 4.1.2 on 2022-10-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0006_rename_social_link_socialmedialinks2_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languagesicons',
            options={'verbose_name_plural': 'About section Languages Icons'},
        ),
        migrations.AlterModelOptions(
            name='socialmedialinks2',
            options={'verbose_name_plural': 'Hero section Social Media Links'},
        ),
    ]
