# Generated by Django 4.1.2 on 2022-10-25 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0007_alter_languagesicons_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialMediaLinks2',
            new_name='SocialMediaLinks',
        ),
    ]
