# Generated by Django 4.1.2 on 2022-11-29 06:14

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0008_rename_socialmedialinks2_socialmedialinks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyProgress',
        ),
        migrations.AlterModelOptions(
            name='languagesicons',
            options={'verbose_name_plural': 'Skills section'},
        ),
        migrations.AddField(
            model_name='languagesicons',
            name='exp_level',
            field=models.CharField(blank=True, max_length=200, verbose_name='Experience Level'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='description_one',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='languagesicons',
            name='icon',
            field=models.CharField(blank=True, max_length=100, verbose_name='language Icon'),
        ),
        migrations.AlterField(
            model_name='languagesicons',
            name='lang_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Language Name'),
        ),
    ]
