# Generated by Django 4.1.2 on 2022-11-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0010_alter_languagesicons_exp_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='description_two',
        ),
        migrations.AlterField(
            model_name='languagesicons',
            name='icon',
            field=models.CharField(blank=True, max_length=100, verbose_name='language Icon Image:( https://icons8.com )'),
        ),
    ]
